name: Terraform Provider Checks

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/terraform_provider.yml
      - provider/**
      - go.sum
      - Makefile
      - main.go

env:
  GO_VERSION: "1.14"
  GO111MODULE: on

jobs:
  pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go with v${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test
        run: make

      - name: Refresh Go Report Card
        if: github.ref == 'refs/heads/main'
        continue-on-error: true
        timeout-minutes: 2
        run: make goreportcard-refresh
